### PR TITLE
Improved Timeout & Retries [minor]

### PR DESCRIPTION
**Pull request by ric-evans**

### CODE REVIEW

**Comment by ric-evans** [comment]
@dsschult I'm not sure about whether using `partial` or how I could handle non-async callables in `auto_retry_call()`

**Comment by dsschult** [comment]
> @dsschult I'm not sure about whether using `partial` or how I could handle non-async callables in `auto_retry_call()`

You want to test the function object using `isawaitable()`, like in https://github.com/WIPACrepo/rest-tools/blob/master/rest_tools/server/decorators.py#L29C12-L29C23

**Comment by ric-evans** [comment]
> > @dsschult I'm not sure about whether using `partial` or how I could handle non-async callables in `auto_retry_call()`
> 
> You want to test the function object using `isawaitable()`, like in [WIPACrepo/rest-tools@`master`/rest_tools/server/decorators.py#L29C12-L29C23](https://github.com/WIPACrepo/rest-tools/blob/master/rest_tools/server/decorators.py?rgh-link-date=2023-07-07T18%3A55%3A48Z#L29C12-L29C23)

Ahh, I was applying that to the callable, not its return value

**Review by dsschult — APPROVED** [review]
I think this looks good?   It's hard to tell exactly, with the same names all over as arguments get passed around.  But I looked at `utils.py` and that looks fine.

**Pull request merged**
